using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace TemporalDDD.Analyzers;

[Generator]
public class ApplicationEventPolymorphismGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var eventDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => s is RecordDeclarationSyntax or ClassDeclarationSyntax,
                transform: GetSemanticTargetForGeneration)
            .Where(t => t != null);

        context.RegisterSourceOutput(context.CompilationProvider.Combine(eventDeclarations.Collect()),
            (spc, source) => Execute(spc, source.Right!));
    }

    private static INamedTypeSymbol? GetSemanticTargetForGeneration(GeneratorSyntaxContext context, CancellationToken ct)
    {
        var declaration = (TypeDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(declaration) as INamedTypeSymbol;

        if (symbol == null || symbol.IsAbstract || symbol.TypeKind == TypeKind.Interface) return null;

        bool implementsInterface = symbol.AllInterfaces.Any(i => i.Name == "IApplicationEvent");
        return implementsInterface ? symbol : null;
    }

    private static void Execute(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> eventSymbols)
    {
        if (eventSymbols.IsDefaultOrEmpty) return;

        // Find the IApplicationEvent interface to get its namespace
        var interfaceSymbol = eventSymbols
            .SelectMany(s => s.AllInterfaces)
            .FirstOrDefault(i => i.Name == "IApplicationEvent");

        if (interfaceSymbol == null) return;

        var interfaceNamespace = interfaceSymbol.ContainingNamespace?.ToString() ?? "TemporalDDD.Application.Messaging";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine($"namespace {interfaceNamespace};");
        sb.AppendLine();
        sb.AppendLine("[JsonPolymorphic(TypeDiscriminatorPropertyName = \"$type\")]");

        foreach (var symbol in eventSymbols.Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default))
        {
            var fullyQualifiedName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var typeName = symbol.Name;
            sb.AppendLine($"[JsonDerivedType(typeof({fullyQualifiedName}), \"{typeName}\")]");
        }

        sb.AppendLine("public partial interface IApplicationEvent { }");
        context.AddSource("IApplicationEvent.g.cs", sb.ToString());
    }
}
