using System;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace TemporalDDD.Analyzers;

[Generator]
public class RebusEventHandlerRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider,
            (spc, compilation) => Execute(spc, compilation));
    }

    private static void Execute(SourceProductionContext context, Compilation compilation)
    {
        // Only generate code for Api project by checking project name
        var isApiProject = compilation.AssemblyName?.Contains("Api", StringComparison.OrdinalIgnoreCase) == true;
        if (!isApiProject) return;

        // Find IEventHandler<> interface
        var eventHandlerInterface = compilation.GetTypeByMetadataName("TemporalDDD.Application.Messaging.IEventHandler`1");
        if (eventHandlerInterface == null) return;

        // Find all types in referenced assemblies AND current compilation that implement IEventHandler<T>
        var handlerRegistrations = new List<(INamedTypeSymbol HandlerType, INamedTypeSymbol EventType)>();
        
        // Scan current compilation's assembly (the Api project itself)
        if (compilation.Assembly != null)
        {
            var types = GetTypesFromNamespace(compilation.Assembly.GlobalNamespace);
            foreach (var type in types)
            {
                if (type.IsAbstract || type.TypeKind == TypeKind.Interface) continue;
                if (type.IsUnboundGenericType) continue; // Skip open generic types
                
                // Find all IEventHandler<T> interfaces this type implements
                foreach (var iface in type.AllInterfaces)
                {
                    if (iface.IsGenericType && iface.ConstructedFrom.Equals(eventHandlerInterface, SymbolEqualityComparer.Default))
                    {
                        var eventType = iface.TypeArguments[0] as INamedTypeSymbol;
                        if (eventType != null)
                        {
                            handlerRegistrations.Add((type, eventType));
                        }
                    }
                }
            }
        }
        
        // Also scan referenced assemblies
        foreach (var reference in compilation.References)
        {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is not IAssemblySymbol assembly) continue;
            
            var types = GetTypesFromNamespace(assembly.GlobalNamespace);
            foreach (var type in types)
            {
                if (type.IsAbstract || type.TypeKind == TypeKind.Interface) continue;
                if (type.IsUnboundGenericType) continue; // Skip open generic types
                
                // Find all IEventHandler<T> interfaces this type implements
                foreach (var iface in type.AllInterfaces)
                {
                    if (iface.IsGenericType && iface.ConstructedFrom.Equals(eventHandlerInterface, SymbolEqualityComparer.Default))
                    {
                        var eventType = iface.TypeArguments[0] as INamedTypeSymbol;
                        if (eventType != null)
                        {
                            handlerRegistrations.Add((type, eventType));
                        }
                    }
                }
            }
        }

        if (handlerRegistrations.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Rebus.Bus;");
        sb.AppendLine("using Rebus.Config;");
        sb.AppendLine("using TemporalDDD.Application.Messaging;");
        sb.AppendLine("using TemporalDDD.Infrastructure.Messaging;");
        sb.AppendLine();
        sb.AppendLine("namespace TemporalDDD.Api;");
        sb.AppendLine();
        sb.AppendLine("public static class GeneratedRebusHandlerRegistrations");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddApplicationEventHandlers(this IServiceCollection services)");
        sb.AppendLine("    {");

        // Group by event type to register adapters only once per event type
        var groupedByEvent = handlerRegistrations
            .GroupBy(x => x.EventType, SymbolEqualityComparer.Default);

        foreach (var group in groupedByEvent)
        {
            var eventType = group.Key;
            var eventTypeName = eventType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            
            // Register each handler implementation as Scoped
            foreach (var (handlerType, _) in group)
            {
                var handlerTypeName = handlerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var handlerInterfaceName = $"global::TemporalDDD.Application.Messaging.IEventHandler<{eventTypeName}>";
                sb.AppendLine($"        services.AddScoped<{handlerInterfaceName}, {handlerTypeName}>();");
            }
            
            // Register the adapter with Rebus (once per event type)
            var adapterTypeStr = $"global::TemporalDDD.Infrastructure.Messaging.RebusEventHandlerAdapter<{eventTypeName}>";
            sb.AppendLine($"        services.AddRebusHandler<{adapterTypeStr}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static async Task SubscribeToApplicationEventsAsync(this WebApplication app)");
        sb.AppendLine("    {");
        sb.AppendLine("        // Resolve the bus from the application's service provider");
        sb.AppendLine("        var bus = app.Services.GetRequiredService<IBus>();");
        sb.AppendLine("        // Establish the broker topic bindings");

        // Get unique event types for subscriptions
        var uniqueEventTypes = handlerRegistrations
            .Select(x => x.EventType)
            .Distinct(SymbolEqualityComparer.Default);

        foreach (var eventType in uniqueEventTypes)
        {
            var eventTypeName = eventType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            sb.AppendLine($"        await bus.Subscribe<{eventTypeName}>();");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedRebusHandlerRegistrations.g.cs", sb.ToString());
    }

    private static IEnumerable<INamedTypeSymbol> GetTypesFromNamespace(INamespaceSymbol namespaceSymbol)
    {
        foreach (var type in namespaceSymbol.GetTypeMembers())
        {
            yield return type;
        }

        foreach (var childNamespace in namespaceSymbol.GetNamespaceMembers())
        {
            foreach (var type in GetTypesFromNamespace(childNamespace))
            {
                yield return type;
            }
        }
    }
}
