using System;
using System.Collections.Generic;
using Microsoft.CodeAnalysis;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace TemporalDDD.Analyzers;

[Generator]
public class RebusEventHandlerRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider,
            (spc, compilation) => Execute(spc, compilation));
    }

    private static void Execute(SourceProductionContext context, Compilation compilation)
    {
        // Only generate code for Infrastructure project by checking project name
        var isInfrastructureProject = compilation.AssemblyName?.Contains("Infrastructure", StringComparison.OrdinalIgnoreCase) == true;
        if (!isInfrastructureProject) return;

        // Find IApplicationEvent interface
        var applicationEventInterface = compilation.GetTypeByMetadataName("TemporalDDD.Application.Messaging.IApplicationEvent");
        if (applicationEventInterface == null) return;

        // Find all types in referenced assemblies that implement IApplicationEvent
        var eventSymbols = new List<INamedTypeSymbol>();
        
        foreach (var reference in compilation.References)
        {
            if (compilation.GetAssemblyOrModuleSymbol(reference) is not IAssemblySymbol assembly) continue;
            
            var types = GetTypesFromNamespace(assembly.GlobalNamespace);
            foreach (var type in types)
            {
                if (type.IsAbstract || type.TypeKind == TypeKind.Interface) continue;
                if (type.AllInterfaces.Any(i => i.Equals(applicationEventInterface, SymbolEqualityComparer.Default)))
                {
                    eventSymbols.Add(type);
                }
            }
        }

        if (eventSymbols.Count == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Rebus.Config;");
        sb.AppendLine("using TemporalDDD.Application.Messaging;");
        sb.AppendLine("using TemporalDDD.Infrastructure.Messaging;");
        sb.AppendLine();
        sb.AppendLine("namespace TemporalDDD.Infrastructure;");
        sb.AppendLine();
        sb.AppendLine("public static class GeneratedRebusHandlerRegistrations");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddApplicationEventHandlers(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var symbol in eventSymbols.Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default))
        {
            var fullyQualifiedName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var adapterTypeStr = $"TemporalDDD.Infrastructure.Messaging.RebusEventHandlerAdapter<{fullyQualifiedName}>";
            sb.AppendLine($"        services.AddRebusHandler<global::{adapterTypeStr}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("GeneratedRebusHandlerRegistrations.g.cs", sb.ToString());
    }

    private static IEnumerable<INamedTypeSymbol> GetTypesFromNamespace(INamespaceSymbol namespaceSymbol)
    {
        foreach (var type in namespaceSymbol.GetTypeMembers())
        {
            yield return type;
        }

        foreach (var childNamespace in namespaceSymbol.GetNamespaceMembers())
        {
            foreach (var type in GetTypesFromNamespace(childNamespace))
            {
                yield return type;
            }
        }
    }
}
