<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\TemporalDDD.Application\TemporalDDD.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Rebus" Version="8.9.2" />
    <PackageReference Include="Rebus.RabbitMq" Version="10.1.1" />
    <PackageReference Include="Rebus.ServiceProvider" Version="10.7.2" />
    <PackageReference Include="Temporalio" Version="1.17.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
