<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
    <PackageReference Include="Temporalio.Extensions.Hosting" Version="1.17.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\DbTemplates\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>DbTemplates\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TemporalDDD.Application\TemporalDDD.Application.csproj" />
    <ProjectReference Include="..\TemporalDDD.Infrastructure\TemporalDDD.Infrastructure.csproj" />
    <ProjectReference Include="..\TemporalDDD.Contracts\TemporalDDD.Contracts.csproj" />
    <ProjectReference Include="..\TemporalDDD.Infrastructure.Queries\TemporalDDD.Infrastructure.Queries.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Analyzer Include="..\TemporalDDD.Analyzers\bin\$(Configuration)\netstandard2.0\TemporalDDD.Analyzers.dll" />
  </ItemGroup>

</Project>
