// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemporalDDD.Infrastructure.Persistence;

#nullable disable

namespace TemporalDDD.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260730062305_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TemporalDDD.Infrastructure.PlacementMatching.AssignmentDbo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("AcceptedAt")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("FacilityId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MatchScore")
                        .HasColumnType("TEXT");

                    b.Property<uint>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProposedAt")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("PublicId IS NOT NULL");

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.PlacementMatching.FacilityDbo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcceptedMedicalBoards")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OvertimeBillRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredSpecialties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StandardBillRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Facilities", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.ProviderCredentialing.CredentialEvaluationDbo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComplianceNotes")
                        .HasColumnType("TEXT");

                    b.Property<long>("EvaluatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompliant")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LicenseExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicalBoard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<uint>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("PublicId IS NOT NULL");

                    b.ToTable("CredentialEvaluations", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.ProviderCredentialing.ProviderProfileDbo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ActivatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("PublicId IS NOT NULL");

                    b.ToTable("ProviderProfiles", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.TimesheetProcessing.TimesheetDbo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GrossPayAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrossPayCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NetPayAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NetPayCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("TEXT");

                    b.Property<long>("PeriodEndUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PeriodStartUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProcessedAt")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SubmittedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("PublicId IS NOT NULL");

                    b.ToTable("Timesheets", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.TravelLogistics.FlightBookingDbo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BookedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CostAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CostCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long>("DepartureTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("PublicId IS NOT NULL");

                    b.ToTable("FlightBookings", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.TravelLogistics.LodgingBookingDbo", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressStreet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("BookedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CostAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CostCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StayPeriodEndUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StayPeriodStartUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("PublicId IS NOT NULL");

                    b.ToTable("LodgingBookings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
