// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemporalDDD.Infrastructure.Persistence;

#nullable disable

namespace TemporalDDD.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260811165118_AddWorkflowTransitions")]
    partial class AddWorkflowTransitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TemporalDDD.Infrastructure.IdentityAndAccess.RoleDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Identity_Roles", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.IdentityAndAccess.UserDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedRolesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Identity_Users", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.PlacementMatching.AssignmentDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("AcceptedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FacilityId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MatchScore")
                        .HasColumnType("TEXT");

                    b.Property<string>("PositionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ProposedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("PublicId IS NOT NULL");

                    b.ToTable("Assignments", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.PlacementMatching.FacilityDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptedMedicalBoards")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OvertimeBillRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequiredSpecialties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StandardBillRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Facilities", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.ProviderCredentialing.CredentialEvaluationDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ComplianceNotes")
                        .HasColumnType("TEXT");

                    b.Property<long>("EvaluatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCompliant")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("LicenseExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicalBoard")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("PublicId IS NOT NULL");

                    b.ToTable("CredentialEvaluations", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.ProviderCredentialing.ProviderProfileDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ActivatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("PublicId IS NOT NULL");

                    b.ToTable("ProviderProfiles", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.TimesheetProcessing.TimesheetDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("GrossPayAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GrossPayCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NetPayAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NetPayCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("TEXT");

                    b.Property<long>("PeriodEndUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PeriodStartUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProcessedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SubmittedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalHours")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("PublicId IS NOT NULL");

                    b.ToTable("Timesheets", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.TravelLogistics.FlightBookingDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("BookedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CostAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CostCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long>("DepartureTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("PublicId IS NOT NULL");

                    b.ToTable("FlightBookings", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.TravelLogistics.LodgingBookingDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressStreet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AddressZipCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("BookedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CostAmount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CostCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StayPeriodEndUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StayPeriodStartUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasFilter("PublicId IS NOT NULL");

                    b.ToTable("LodgingBookings", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.WorkflowOrchestration.WorkflowDefinitionDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FlowJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassName")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Workflow_Definitions", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.WorkflowOrchestration.WorkflowInstanceDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessReferenceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemporalRunId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowDefinitionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasAlternateKey("PublicId");

                    b.ToTable("Workflow_Instances", (string)null);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.WorkflowOrchestration.WorkflowNodeDbo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BusinessNotes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfigured")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NodeType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkflowDefinitionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("Workflow_Nodes", (string)null);

                    b.HasDiscriminator<int>("NodeType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.WorkflowOrchestration.WorkflowTransitionDbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceNodeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetNodeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowDefinitionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("WorkflowTransitions");
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.WorkflowOrchestration.ApiWorkflowNodeDbo", b =>
                {
                    b.HasBaseType("TemporalDDD.Infrastructure.WorkflowOrchestration.WorkflowNodeDbo");

                    b.Property<string>("AuthToken")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("ContractMappingConvertXmlToJson")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractMappingQueryParameters")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractMappingRequestMapping")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractMappingResponseMapping")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndpointUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RetryPolicyBackoffCoefficient")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RetryPolicyMaxAttempts")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.WorkflowOrchestration.HumanTaskWorkflowNodeDbo", b =>
                {
                    b.HasBaseType("TemporalDDD.Infrastructure.WorkflowOrchestration.WorkflowNodeDbo");

                    b.Property<string>("RequiredRole")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TimeoutInMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UIFormSchema")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.WorkflowOrchestration.NotificationWorkflowNodeDbo", b =>
                {
                    b.HasBaseType("TemporalDDD.Infrastructure.WorkflowOrchestration.WorkflowNodeDbo");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.WorkflowOrchestration.WorkflowNodeDbo", b =>
                {
                    b.HasOne("TemporalDDD.Infrastructure.WorkflowOrchestration.WorkflowDefinitionDbo", null)
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TemporalDDD.Infrastructure.WorkflowOrchestration.WorkflowTransitionDbo", b =>
                {
                    b.HasOne("TemporalDDD.Infrastructure.WorkflowOrchestration.WorkflowDefinitionDbo", null)
                        .WithMany()
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
