using Temporalio.Workflows;
using TemporalDDD.Application.TimesheetProcessing;
using TemporalDDD.Domain.SharedKernel;
using TemporalDDD.Domain.TimesheetProcessing;
using TemporalDDD.Domain.TimesheetProcessing.ValueObjects;

namespace TemporalDDD.Application.TimesheetProcessing;

[Workflow]
public class TimesheetProcessingWorkflow
{
    [WorkflowRun]
    public async Task RunAsync(TimesheetProcessingInput input)
    {
        // Elevate to Domain types with catastrophic assertions
        var providerIdResult = ProviderId.Create(input.ProviderId);
        if (providerIdResult.IsFailure)
            throw new InvalidOperationException($"Internal Corruption: Invalid ProviderId. {providerIdResult.Error}");

        var periodStart = DateTimeOffset.FromUnixTimeMilliseconds(input.PeriodStartUtc);
        var periodEnd = DateTimeOffset.FromUnixTimeMilliseconds(input.PeriodEndUtc);
        var periodResult = DateRange.Create(periodStart, periodEnd);
        if (periodResult.IsFailure)
            throw new InvalidOperationException($"Internal Corruption: Invalid DateRange. {periodResult.Error}");

        var totalHoursResult = Hours.Create(input.TotalHours);
        if (totalHoursResult.IsFailure)
            throw new InvalidOperationException($"Internal Corruption: Invalid Hours. {totalHoursResult.Error}");

        var hourlyRateResult = HourlyRate.Create(input.HourlyRate);
        if (hourlyRateResult.IsFailure)
            throw new InvalidOperationException($"Internal Corruption: Invalid HourlyRate. {hourlyRateResult.Error}");

        var facilityBillRateResult = Money.Create(input.FacilityBillRateAmount, input.FacilityBillRateCurrency);
        if (facilityBillRateResult.IsFailure)
            throw new InvalidOperationException($"Internal Corruption: Invalid Money. {facilityBillRateResult.Error}");

        var providerId = providerIdResult.Value;
        var period = periodResult.Value;
        var totalHours = totalHoursResult.Value;
        var hourlyRate = hourlyRateResult.Value;
        var facilityBillRate = facilityBillRateResult.Value;
        // Step 1: Validate Timesheet Rules
        var timesheetId = TimesheetId.Create(1).Value!; // In real scenario, this would be generated by DB
        await Workflow.ExecuteActivityAsync(
            (ITimesheetProcessingActivities activities) => activities.ValidateTimesheetRulesAsync(new ValidateTimesheetInput(timesheetId.Value)),
            new ActivityOptions { StartToCloseTimeout = TimeSpan.FromMinutes(5) }
        );

        // Step 2: Calculate Payroll and Taxes
        var payrollResult = await Workflow.ExecuteActivityAsync(
            (ITimesheetProcessingActivities activities) => activities.CalculatePayrollAndTaxesAsync(new CalculatePayrollInput(timesheetId.Value)),
            new ActivityOptions { StartToCloseTimeout = TimeSpan.FromMinutes(5) }
        );

        // Step 3: Submit Bank Transfer with Idempotency Key
        // IMPORTANT: Pass Workflow.Info.WorkflowId as idempotency key for payment gateway
        var idempotencyKey = Workflow.Info.WorkflowId;
        var paymentReference = await Workflow.ExecuteActivityAsync(
            (ITimesheetProcessingActivities activities) => activities.SubmitBankTransferAsync(new SubmitBankTransferInput(timesheetId.Value, idempotencyKey)),
            new ActivityOptions { StartToCloseTimeout = TimeSpan.FromMinutes(10) }
        );

        Console.WriteLine($"[TimesheetProcessing] Payment submitted with reference: {paymentReference}");

        // Step 4: Generate and Send Invoice to ERP System
        var invoiceNumber = await Workflow.ExecuteActivityAsync(
            (ITimesheetProcessingActivities activities) => activities.GenerateAndSendInvoiceAsync(new GenerateInvoiceInput(timesheetId.Value, facilityBillRate.Amount)),
            new ActivityOptions { StartToCloseTimeout = TimeSpan.FromMinutes(5) }
        );

        Console.WriteLine($"[TimesheetProcessing] Invoice generated: {invoiceNumber}");
    }
}
