using Temporalio.Workflows;
using TemporalDDD.Application.TimesheetProcessing;
using TemporalDDD.Domain.SharedKernel;
using TemporalDDD.Domain.TimesheetProcessing;
using TemporalDDD.Domain.TimesheetProcessing.ValueObjects;

namespace TemporalDDD.Application.TimesheetProcessing;

[Workflow]
public class TimesheetProcessingWorkflow
{
    [WorkflowRun]
    public async Task RunAsync(TimesheetProcessingInput input)
    {
        // Pass-through: No domain conversion needed - just pass primitives to activities
        // Step 1: Validate Timesheet Rules
        var timesheetId = TimesheetId.Create(1).Value!; // In real scenario, this would be generated by DB
        await Workflow.ExecuteActivityAsync(
            (ITimesheetProcessingActivities activities) => activities.ValidateTimesheetRulesAsync(new ValidateTimesheetInput(timesheetId.Value)),
            new ActivityOptions { StartToCloseTimeout = TimeSpan.FromMinutes(5) }
        );

        // Step 2: Calculate Payroll and Taxes
        var payrollResult = await Workflow.ExecuteActivityAsync(
            (ITimesheetProcessingActivities activities) => activities.CalculatePayrollAndTaxesAsync(new CalculatePayrollInput(timesheetId.Value)),
            new ActivityOptions { StartToCloseTimeout = TimeSpan.FromMinutes(5) }
        );

        // Convert primitive payroll result to domain types for business logic
        var grossPay = Money.Create(payrollResult.GrossPayAmount, payrollResult.GrossPayCurrency).Value!;
        var taxAmount = Money.Create(payrollResult.TaxAmount, payrollResult.TaxCurrency).Value!;
        var netPay = Money.Create(payrollResult.NetPayAmount, payrollResult.NetPayCurrency).Value!;

        // Step 3: Submit Bank Transfer with Idempotency Key
        // IMPORTANT: Pass Workflow.Info.WorkflowId as idempotency key for payment gateway
        var idempotencyKey = Workflow.Info.WorkflowId;
        var paymentReference = await Workflow.ExecuteActivityAsync(
            (ITimesheetProcessingActivities activities) => activities.SubmitBankTransferAsync(new SubmitBankTransferInput(timesheetId.Value, idempotencyKey)),
            new ActivityOptions { StartToCloseTimeout = TimeSpan.FromMinutes(10) }
        );

        Console.WriteLine($"[TimesheetProcessing] Payment submitted with reference: {paymentReference}");

        // Step 4: Generate and Send Invoice to ERP System
        var invoiceNumber = await Workflow.ExecuteActivityAsync(
            (ITimesheetProcessingActivities activities) => activities.GenerateAndSendInvoiceAsync(new GenerateInvoiceInput(timesheetId.Value, netPay.Amount)),
            new ActivityOptions { StartToCloseTimeout = TimeSpan.FromMinutes(5) }
        );

        Console.WriteLine($"[TimesheetProcessing] Invoice generated: {invoiceNumber}");
    }
}
